---
# tasks file for wdijkerman.zabbix

#TODO Put this in specific os file?
- name: Installing release.rpm
  shell: rpm -ivh http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm
         creates=/etc/yum.repos.d/zabbix.repo 
  tags:
    - zabbix-server

- name: Installing zabbix-server-{{ database_type }}
  yum: pkg=zabbix-server-{{ database_type }} state=present
  tags: zabbix-server

- name: Installing the zabbix-server package
  yum: pkg=zabbix-server state=present
  tags: zabbix-server

- name: Configure zabbix-server
  template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf mode=0755 owner=zabbix group=zabbix
  notify: zabbix-server restarted
  tags: zabbix-server

- name: Create include dir zabbix-server
  file: path={{ server_include }} owner=zabbix group=zabbix state=directory
  tags: zabbix-server

