---
# Tasks specific for RedHat systems

- name: Set some RH facts
  set_fact: 
    apache_log: httpd
    datafiles_path: "/usr/share/doc/zabbix-server-{{ database_type }}-{{ zabbix_version }}*/create"

- name: Install RH basic repo file
  template: src=rhel.repo.j2
            dest=/etc/yum.repos.d/zabbix.repo
            owner=root 
            group=root 
            mode=0644

- name: Installing RH zabbix-server-{{ database_type }}
  yum:  pkg=zabbix-server-{{ database_type }} 
        state=present

- name: Install RH zabbix-web-{{ database_type }}
  yum:  pkg=zabbix-web-{{ database_type }} 
        state=present

- name: install RH apache vhost
  template: src=apache_vhost.conf.j2
            dest=/etc/httpd/conf.d/zabbix.conf
            owner=root
            group=root
            mode=0644
  notify: restart apache
