---
# Tasks specific for RedHat systems

- name: "RedHat | Set some facts"
  set_fact:
    apache_log: httpd
    datafiles_path: "/usr/share/doc/zabbix-server-{{ database_type }}-{{ zabbix_version }}*/create"

- name: "RedHat | Install basic repo file"
  template: src=rhel.repo.j2
            dest=/etc/yum.repos.d/zabbix.repo
            owner=root
            group=root
            mode=0644
  when: zabbix_repo

- name: "RedHat | Installing zabbix-server-{{ database_type }}"
  yum:  pkg=zabbix-server-{{ database_type }}
        state=present

- name: "RedHat | Install zabbix-web-{{ database_type }}"
  yum:  pkg=zabbix-web-{{ database_type }}
        state=present
  when: zabbix_web

- name: "RedHat | Install apache vhost"
  template: src=apache_vhost.conf.j2
            dest=/etc/httpd/conf.d/zabbix.conf
            owner=root
            group=root
            mode=0644
  when: zabbix_vhost and zabbix_web
  notify: restart apache

- name: "RedHat | Install Ansible module dependencies"
  yum: name=python-psycopg2
       state=present
  when: zabbix_database_creation

- name: "RedHat | Install Mysql Client package RHEL7"
  yum: name=mariadb state=present
  when: ansible_distribution_major_version == "7" and database_type == 'mysql'

- name: "RedHat | Install Mysql Client package RHEL5 - 6"
  yum: name=mysql
       state=present
  when: database_type == 'mysql' and ansible_distribution_major_version == "6" or ansible_distribution_major_version == "5"

- name: "RedHat | Install PostgreSQL client package"
  yum: name=postgresql
       state=latest
  when: database_type == 'pgsql'

